version: 2.1

orbs:
    # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
    node: circleci/node@5.0.2

executors:
    default:
        docker:
            - image: cimg/node:lts

jobs:
    test:
        executor: default
        steps:
            - checkout
            - node/install-packages
            - run: npm test

    release:
        executor: default
        steps:
            - checkout
            - node/install-packages
            - run: npx semantic-release

workflows:
    build:
        jobs:
            - test
            - release:
                  context: github-release
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - main
