aliases:
    - &dir ~/repo
    - &defaults
      working_directory: *dir
      docker:
          - image: circleci/node:lts
    - &cache_key
      key: dependency-cache-{{ checksum "package.json" }}
    - &attach_workspace
      attach_workspace:
          at: *dir

version: 2
jobs:
    checkout_code:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache_key
            - run: npm install
            - save_cache:
                  <<: *cache_key
                  paths:
                      - ./node_modules
            - persist_to_workspace:
                  root: *dir
                  paths:
                      - .

    test:
        <<: *defaults
        steps:
            - *attach_workspace
            - run: npm run lint
            - run: npm test

    release:
        <<: *defaults
        steps:
            - *attach_workspace
            # - checkout # Commenting this line out as I don't think it is needed, please uncomment if the release fails
            - run: npm run semantic-release

workflows:
    version: 2
    build:
        jobs:
            - checkout_code
            - test:
                  requires:
                      - checkout_code
            - release:
                  context: org-global
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
