version: 2.1

orbs:
    node: circleci/node@5.1.0
    release: fiveapp/release@0

workflows:
    build:
        jobs:
            - node/test
            - release/npm_and_github:
                  build_command: npm run build
                  context:
                      - org-global
                      - github-release
                  requires:
                      - node/test
                  filters:
                      branches:
                          only:
                              - main
